; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf
upload_protocol = custom
upload_speed = 460800
upload_port = COM5
board_upload.flash_size = 16MB
board_upload.maximum_size = 4194304
board_build.memory_type = qio_opi
board_build.psram_type = opi
extra_scripts =
    pre:tools/configure_upload.py
lib_deps =
    lvgl/lvgl@8.3.11
build_unflags =
    -Os
build_flags =
    -DSDKCONFIG_DEFAULTS=\"sdkconfig.defaults\"
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -I .pio/libdeps/esp32-s3-devkitm-1/lvgl
    -I .pio/libdeps/esp32-s3-devkitm-1/lvgl/src
    -O0
