#ifndef APP_USB_AUDIO_DESCRIPTORS_H
#define APP_USB_AUDIO_DESCRIPTORS_H

#include <stdint.h>

#include "tinyusb.h"

#define APP_USB_AUDIO_SAMPLE_RATE_HZ 48000U
#define APP_USB_AUDIO_CHANNEL_COUNT 2U
#define APP_USB_AUDIO_BYTES_PER_SAMPLE 2U
#define APP_USB_AUDIO_BITS_PER_SAMPLE 16U

#define APP_USB_AUDIO_ENTITY_CLOCK 0x04
#define APP_USB_AUDIO_ENTITY_INPUT_TERMINAL 0x01
#define APP_USB_AUDIO_ENTITY_FEATURE_UNIT 0x02
#define APP_USB_AUDIO_ENTITY_OUTPUT_TERMINAL 0x03

enum {
    APP_USB_AUDIO_ITF_AUDIO_CONTROL = 0,
    APP_USB_AUDIO_ITF_AUDIO_STREAMING,
    APP_USB_AUDIO_ITF_TOTAL,
};

#define APP_USB_AUDIO_SPEAKER_STEREO_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN \
    + TUD_AUDIO_DESC_STD_AC_LEN \
    + TUD_AUDIO_DESC_CS_AC_LEN \
    + TUD_AUDIO_DESC_CLK_SRC_LEN \
    + TUD_AUDIO_DESC_INPUT_TERM_LEN \
    + TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
    + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN \
    + TUD_AUDIO_DESC_STD_AS_INT_LEN \
    + TUD_AUDIO_DESC_STD_AS_INT_LEN \
    + TUD_AUDIO_DESC_CS_AS_INT_LEN \
    + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN \
    + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN \
    + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN)

#define APP_USB_AUDIO_SPEAKER_STEREO_DESCRIPTOR(_itfnum, _stridx, _n_bytes_per_sample, _n_bits_used_per_sample, _epout, _epoutsize) \
    TUD_AUDIO_DESC_IAD((_itfnum), 0x02, 0x00), \
    TUD_AUDIO_DESC_STD_AC((_itfnum), 0x00, (_stridx)), \
    TUD_AUDIO_DESC_CS_AC(0x0200, AUDIO_FUNC_DESKTOP_SPEAKER, TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN, AUDIO_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
    TUD_AUDIO_DESC_CLK_SRC(APP_USB_AUDIO_ENTITY_CLOCK, AUDIO_CLOCK_SOURCE_ATT_INT_FIX_CLK, (AUDIO_CTRL_R << AUDIO_CLOCK_SOURCE_CTRL_CLK_FRQ_POS), APP_USB_AUDIO_ENTITY_INPUT_TERMINAL, 0x00), \
    TUD_AUDIO_DESC_INPUT_TERM(APP_USB_AUDIO_ENTITY_INPUT_TERMINAL, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, APP_USB_AUDIO_ENTITY_CLOCK, APP_USB_AUDIO_CHANNEL_COUNT, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0x0000, 0x00), \
    TUD_AUDIO_DESC_OUTPUT_TERM(APP_USB_AUDIO_ENTITY_OUTPUT_TERMINAL, AUDIO_TERM_TYPE_OUT_DESKTOP_SPEAKER, APP_USB_AUDIO_ENTITY_INPUT_TERMINAL, APP_USB_AUDIO_ENTITY_FEATURE_UNIT, APP_USB_AUDIO_ENTITY_CLOCK, 0x0000, 0x00), \
    TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL(APP_USB_AUDIO_ENTITY_FEATURE_UNIT, APP_USB_AUDIO_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), 0x00, 0x00, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), 0x01, 0x01, 0x00), \
    TUD_AUDIO_DESC_CS_AS_INT(APP_USB_AUDIO_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, AUDIO_DATA_FORMAT_TYPE_I_PCM, APP_USB_AUDIO_CHANNEL_COUNT, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
    TUD_AUDIO_DESC_TYPE_I_FORMAT((_n_bytes_per_sample), (_n_bits_used_per_sample)), \
    TUD_AUDIO_DESC_STD_AS_ISO_EP((_epout), (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ADAPTIVE | TUSB_ISO_EP_ATT_DATA), (_epoutsize), 0x01), \
    TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, 0x0000)

const tinyusb_desc_config_t *app_usb_audio_descriptors_get_config(void);

#endif
