#pragma once

#include_next "tusb_config.h"

#undef CFG_TUSB_DEBUG
#define CFG_TUSB_DEBUG 0

#undef CFG_TUD_CDC
#define CFG_TUD_CDC 0

#undef CFG_TUD_MSC
#define CFG_TUD_MSC 0

#undef CFG_TUD_HID
#define CFG_TUD_HID 0

#undef CFG_TUD_MIDI
#define CFG_TUD_MIDI 0

#undef CFG_TUD_VENDOR
#define CFG_TUD_VENDOR 0

#ifdef CFG_TUD_NCM
#undef CFG_TUD_NCM
#define CFG_TUD_NCM 0
#endif

#undef CFG_TUD_AUDIO
#define CFG_TUD_AUDIO 1

#undef CFG_TUD_AUDIO_FUNC_1_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN 136

#undef CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ
#define CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ 64

#undef CFG_TUD_AUDIO_ENABLE_EP_OUT
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1

#undef CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP 0

#undef CFG_TUD_AUDIO_ENABLE_FEEDBACK_FORMAT_CORRECTION
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_FORMAT_CORRECTION 0

#undef CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX 2

#undef CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX
#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX 2

#undef CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX
#define CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX 16

#undef CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE
#define CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE 48000

#undef CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX 192

#undef CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ 4096
