#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define BOARD_LCD_HOST SPI2_HOST

#define BOARD_LCD_HOR_RES 320
#define BOARD_LCD_VER_RES 240
#define BOARD_LCD_DRAW_BUF_LINES 30

#define BOARD_LCD_PIN_MISO GPIO_NUM_13
#define BOARD_LCD_PIN_MOSI GPIO_NUM_11
#define BOARD_LCD_PIN_CLK GPIO_NUM_12
#define BOARD_LCD_PIN_CS GPIO_NUM_10
#define BOARD_LCD_PIN_DC GPIO_NUM_17
#define BOARD_LCD_PIN_RST GPIO_NUM_16

#define BOARD_TOUCH_PIN_CS GPIO_NUM_8
#define BOARD_TOUCH_SPI_CLOCK_HZ (2 * 1000 * 1000)
#define BOARD_TOUCH_THRESHOLD 35

#define BOARD_TOUCH_CAL_X_OFFSET 1830
#define BOARD_TOUCH_CAL_Y_OFFSET 1717
#define BOARD_TOUCH_CAL_X_SCALE (-0.178230f)
#define BOARD_TOUCH_CAL_Y_SCALE (-0.131406f)
#define BOARD_TOUCH_CAL_SCREEN_X_OFFSET 20
#define BOARD_TOUCH_CAL_SCREEN_Y_OFFSET 20

#define BOARD_AUDIO_I2S_NUM I2S_NUM_0
#define BOARD_AUDIO_SAMPLE_RATE 16000
#define BOARD_AUDIO_BCLK_GPIO GPIO_NUM_5
#define BOARD_AUDIO_WS_GPIO GPIO_NUM_6
#define BOARD_AUDIO_DATA_IN_GPIO GPIO_NUM_4
#define BOARD_AUDIO_MIC_USE_LEFT_SLOT 1

#endif
